### ISSUE TITLE
[FE] 게임 list에 시간이랑 게임타입 드러나게 ui 변경

### ISSUE THREAD

**Issue by jinbekim** [Heosejin98/Xmash#100]

**Comment by Seheo998** [comment]
![image](https://github.com/user-attachments/assets/f2c2c433-55f0-421d-96f2-b77a14c47ecf)
이거 희연님이 피드백 주셨었는데
저는 빨간 동그리미 친 부분에 시간 정보 있으면 좋을 것 같습니다.
게임 타입(단식, 복식)은  그냥 한눈에 알아보기 힘들어서 바꾸는건가요? 어짜피 2명있으면 복식인지 알 것 같아서 
단식 - A색생 , 복식 - B색상 색상으로 표시되면 좋을 것 같은데 저기 더 넣을 공간도 없어보여서

**Comment by jinbekim** [comment]
<img width="298" alt="image" src="https://github.com/user-attachments/assets/3ca44853-0287-443b-aefd-1720baec83cd">
