### ISSUE TITLE
[FE] 게임 등록 시나리오 변경 및 ui 변경

### ISSUE THREAD

**Issue by jinbekim** [Heosejin98/Xmash#101]

**Comment by Seheo998** [comment]
로그인 안했을때 아래 동그라미 친 부분 invisible 처리 될까요

![image](https://github.com/user-attachments/assets/38c9841e-53cc-4932-bdcb-cdf7bfd59698)

**Comment by jinbekim** [comment]
![Uploading image.png…]()
